src/BlogApp/Areas/Admin/Controllers/EventsController.cs
using BlogApp.Areas.Admin.Models;
using BlogApp.EF.Tables;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "Admin")]
    public class EventsController : BaseController
    {
        Repositories.Repository<Event> EventRepo = new Repositories.Repository<Event>();

        public IActionResult Index()
        {
            List<Event> categories = EventRepo.All();
            return View(categories.Select(Event => new EventModel()
            {
                Id = Event.Id,
                EventName = Event.EventName,
                Description = Event.Description
            }).ToList());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(EventModel model)
        {
            if (ModelState.IsValid)
            {
                string imageUrl = await StorageHelper.Instance.UploadFile(model.MainImage.OpenReadStream(), model.EventName.FriendlyUrl());
                if (EventRepo.Add(new EF.Tables.Event()
                {
                    Content = model.Content,
                    CreatedDate = DateTime.Now,
                    EventName = model.EventName,
                    Description = model.Description,
                    MainImage = imageUrl
                }))
                    return Success("Etkinlik başarılı bri şekilde eklendi.", model);
                else
                    return Error("Etkinlik eklenirken hata oluştu.", model);
            }
            return View(model);
        }

        public IActionResult Edit(Nullable<Guid> Id)
        {
            if (!Id.HasValue)
                return RedirectToAction("Index");
            Event Event = EventRepo.Single(a => a.Id == Id.Value);
            if (Event == null)
                return RedirectToAction("Index");
            return View(new EventModel()
            {
                Id = Event.Id,
                EventName = Event.EventName
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EventModel model)
        {
            if (ModelState.IsValid)
            {
                string imageUrl = await StorageHelper.Instance.UploadFile(model.MainImage.OpenReadStream(), model.EventName.FriendlyUrl());
                if (EventRepo.Update(new EF.Tables.Event()
                {
                    Id = model.Id,
                    EventName = model.EventName,
                    Url = model.EventName.FriendlyUrl(),
                    Description = model.Description,
                    Content = model.Content,
                    MainImage = imageUrl
                }))
                    return Success("Etkinlik başarılı bir şekilde güncellendi.", model);
                else
                    return Error("Etkinlik güncellenirken hata oluştu.", model);
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult Delete(Nullable<Guid> Id)
        {
            if (!Id.HasValue) return Json("Etkinlik bulunamadı.");
            Event Event = EventRepo.Single(a => a.Id == Id.Value);
            if (Event == null)
                return Json("Etkinlik Bulunamadı.");
            if (EventRepo.Delete(Event))
                return Json("Etkinlik başarılı bir şekilde silindi.");
            else
                return Json("Etkinlik silinirken bir hata oluştu.");
        }
    }
}

src/BlogApp/Areas/Admin/Views/Events/Add.cshtml
@model BlogApp.Areas.Admin.Models.EventModel
@{
    bool IsError = false;
    bool IsMessage = false;
    string Message = "", Error = "";
    ViewBag.Title = "Yeni Etkinlik Ekle";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="Event-header">Etkinlik Ekle</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Yeni Etkinlik Ekle
            </div>
            <div class="panel-body">
                @if (IsError)
                {
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Error
                    </div>
                }
                else if (IsMessage)
                {
                    <div class="alert alert-success alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Message
                    </div>
                }
                <div class="row">
                    @using (Html.BeginForm("Add", "Events", new { area = "Admin" }, FormMethod.Post, true, new { role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="col-lg-10">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title)
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Title) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Description)
                                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = 2, placeholder = Html.DisplayNameFor(model => model.Description) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.EventImage)
                                <input type="file" name="EventImage" id="EventImage" class="form-control" />
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Content)
                                @Html.TextAreaFor(model => model.Content, new { @class = "form-control tinymce", rows = 10, placeholder = Html.DisplayNameFor(model => model.Content) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Tags)
                                @Html.TextBoxFor(model => model.Tags, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Tags) })
                            </div>
                            <button type="submit" class="btn btn-success">Yeni Etkinlik Ekle</button>
                            <button type="reset" class="btn btn-danger">İptal</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Admin/vendor/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '.tinymce',
            height: 500,
            theme: 'modern',
            plugins: [
              'advlist autolink lists link image charmap print preview hr anchor Eventbreak',
              'searchreplace wordcount visualblocks visualchars code fullscreen',
              'insertdatetime media nonbreaking save table contextmenu directionality',
              'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc example'
            ],
            toolbar1: 'example | undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons | codesample | code',
            image_advtab: true,
            templates: [
              { title: 'Test template 1', content: 'Test 1' },
              { title: 'Test template 2', content: 'Test 2' }
            ],
            content_css: [
              '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
              '//www.tinymce.com/css/codepen.min.css'
            ]
        });
    </script>
}

src/BlogApp/Areas/Admin/Views/Events/Edit.cshtml
@model BlogApp.Areas.Admin.Models.PageModel
@{
    bool IsError = false;
    bool IsMessage = false;
    string Message = "", Error = "";
    ViewBag.Title = "Sayfa Güncelle";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Sayfa Güncelle</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Sayfayı Güncelle
            </div>
            <div class="panel-body">
                @if (IsError)
                {
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Error
                    </div>
                }
                else if (IsMessage)
                {
                    <div class="alert alert-success alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Message
                    </div>
                }
                <div class="row">
                    @using (Html.BeginForm("Edit", "Pages", new { area = "Admin" }, FormMethod.Post, true, new { role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.Id)
                        <div class="col-lg-10">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title)
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Title) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Description)
                                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = 2, placeholder = Html.DisplayNameFor(model => model.Description) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.PageImage)
                                <input type="file" name="PageImage" id="PageImage" class="form-control" />
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Content)
                                @Html.TextAreaFor(model => model.Content, new { @class = "form-control tinymce", rows = 10, placeholder = Html.DisplayNameFor(model => model.Content) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Tags)
                                @Html.TextBoxFor(model => model.Tags, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Tags) })
                            </div>
                            <button type="submit" class="btn btn-success">Sayfayı Güncelle</button>
                            <button type="reset" class="btn btn-danger">İptal</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/Admin/vendor/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '.tinymce',
            height: 500,
            theme: 'modern',
            plugins: [
              'advlist autolink lists link image charmap print preview hr anchor pagebreak',
              'searchreplace wordcount visualblocks visualchars code fullscreen',
              'insertdatetime media nonbreaking save table contextmenu directionality',
              'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc example'
            ],
            toolbar1: 'example | undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
            toolbar2: 'print preview media | forecolor backcolor emoticons | codesample | code',
            image_advtab: true,
            templates: [
              { title: 'Test template 1', content: 'Test 1' },
              { title: 'Test template 2', content: 'Test 2' }
            ],
            content_css: [
              '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
              '//www.tinymce.com/css/codepen.min.css'
            ]
        });
    </script>
}

src/BlogApp/Areas/Admin/Views/Events/Index.cshtml
@model List<BlogApp.Areas.Admin.Models.EventModel>
@{
    ViewBag.Title = "Etkinliklar";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="Event-header">Etkinliklar</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Etkinlik Listesi
                <a type="button" asp-controller="Events" asp-action="Add" class="btn btn-primary btn-sm pull-right">Yeni Etkinlik Ekle</a>
            </div>
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>Etkinlik Adı</th>
                            <th>Etkinlik Açıklama</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var Event in Model)
                        {
                            <tr class="odd gradeX">
                                <td>
                                    @Html.ActionLink(Event.EventName, "Event", "Home", new { area = "", id = Event.FriendlyUrl }, new { target = "_blank" })
                                </td>
                                <td>@Event.Description</td>
                                <td class="center">
                                    @Html.ActionLink("Düzenle", "Edit", new { Id = Event.Id })
                                    <button onclick="Publish('@Event.Id')">Yayınla</button>
                                    <button onclick="Delete('@Event.Id')">Sil</button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Styles{
    <!-- DataTables CSS -->
    <link href="/assets/admin/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="/assets/admin/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

}

@section Scripts{
    <!-- DataTables JavaScript -->
    <script src="/assets/admin/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/assets/admin/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/assets/admin/vendor/datatables-responsive/dataTables.responsive.js"></script>

    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });

        function Publish(id) {
            if (confirm("Etkinliği yayınlamak istediğinizden emin misiniz?")) {
                $.ajax({
                    method: 'POST',
                    url: '@Url.Action("Publish", "Events")',
                    data: 'Id=' + id,
                    success: function (result) {
                        alert(result);
                        location.reload();
                    },
                    error: function (error) {
                        alert(error);
                    }
                });
            }
        }

        function Delete(id) {
            if (confirm("Etkinlikyı silmek istediğinizden emin misiniz?")) {
                $.ajax({
                    method: 'POST',
                    url: '@Url.Action("Delete", "Events")',
                    data: 'Id=' + id,
                    success: function (result) {
                        alert(result);
                        location.reload();
                    },
                    error: function (error) {
                        alert(error);
                    }
                });
            }
        }
    </script>
}