src/BlogApp/Areas/Admin/Controllers/AuthorsController.cs
using BlogApp.Areas.Admin.Models;
using BlogApp.EF.Tables;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlogApp.Areas.Admin.Controllers
{
    [Authorize(Policy = "Admin")]
    [Area("Admin")]
    public class AuthorsController : BaseController
    {
        Repositories.Repository<Author> AuthorRepo = new Repositories.Repository<Author>();

        public IActionResult Index()
        {
            var authorList = AuthorRepo.All();
            return View(authorList.Select(author => new Models.AuthorListModel()
            {
                Email = author.Email,
                FullName = author.FullName,
                ProfileImage = author.ProfileImage,
                Id = author.Id,
                Title = author.Title
            }).ToList());
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(AuthorModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Password != model.ConfirmPassword)
                    return Error("Şifreleriniz eşleşmiyor!", model);
                Author author = AuthorRepo.Single(a => a.Username == model.Username.ToLower() | a.Email == model.Email.ToLower());

                if (author != null)
                    return Error("Bu yazar önceden kaydedilmiştir.", model);

                if (AuthorRepo.Add(new Author()
                {
                    Email = model.Email,
                    FullName = model.NameSurname,
                    CreatedDate = DateTime.Now,
                    Id = Guid.NewGuid(),
                    Password = model.Password.Hash(),
                    Username = model.Username.ToLower(),
                    ProfileImage = "",
                    Title = model.Title,
                    SocialMediaJSON = new SocialMediaHelper(model.Facebook, model.Twitter, model.Github, model.LinkedIn, model.WebSite).ToJSON()
                }))
                    return Success("Yazar başarılı bir şekilde eklendi.");
                else
                    return Error("Yazar eklenirken hata oluştu");
            }
            return View(model);
        }

        public IActionResult Edit(Nullable<Guid> Id)
        {
            if (!Id.HasValue)
                return RedirectToAction("Index");
            Author author = AuthorRepo.Single(a => a.Id == Id.Value);
            if (author == null)
                return RedirectToAction("Index");
            SocialMediaHelper socialMedia = new Admin.SocialMediaHelper(author.SocialMediaJSON);
            return View(new AuthorModel()
            {
                Id = author.Id,
                NameSurname = author.FullName,
                Email = author.Email,
                Title = author.Title,
                Username = author.Username.ToLower(),
                Facebook = socialMedia.Get("facebook")?.Url,
                Twitter = socialMedia.Get("twitter")?.Url,
                Github = socialMedia.Get("github")?.Url,
                LinkedIn = socialMedia.Get("linkedin")?.Url
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AuthorModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Password != model.ConfirmPassword)
                    return Error("Şifreler birbiri ile uyuşmamaktadır.", model);
                if (AuthorRepo.Update(new EF.Tables.Author()
                {
                    Id = model.Id,
                    Email = model.Email,
                    FullName = model.NameSurname,
                    Password = model.Password.Hash(),
                    SocialMediaJSON = new SocialMediaHelper(
                            model.Facebook,
                            model.Twitter,
                            model.Github,
                            model.LinkedIn
                        ).ToJSON(),
                    Title = model.Title,
                    Username = model.Username
                }))
                    return Success("Yazar başarılı bir şekilde güncellendi.", model);
                else
                    return Error("Yazar güncellenirken bir hata oluştu.", model);
            }
            return View(model);
        }

        [HttpPost]
        public JsonResult Delete(Nullable<Guid> Id)
        {
            if (!Id.HasValue) return Json("Yazar bulunamadı.");
            Author author = AuthorRepo.Single(a => a.Id == Id.Value);
            if (author == null)
                return Json("Yazar Bulunamadı.");
            if (AuthorRepo.Delete(author))
                return Json("Yazar başarılı bir şekilde silindi.");
            else
                return Json("Yazar silinirken bir hata oluştu.");
        }
    }
}

src/BlogApp/Areas/Admin/Views/Authors/Add.cshtml
@model BlogApp.Areas.Admin.Models.AuthorModel
@{
    bool IsError = false;
    bool IsMessage = false;
    string Message = "", Error = "";
    ViewBag.Title = "Yeni Yazar Ekle";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Yazar Ekle</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Yeni Yazar Ekle
            </div>
            <div class="panel-body">
                @if (IsError)
                {
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Error
                    </div>
                }
                else if (IsMessage)
                {
                    <div class="alert alert-success alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Message
                    </div>
                }
                <div class="row">
                    @using (Html.BeginForm("Add", "Authors", new { area = "Admin" }, FormMethod.Post, true, new { role = "form" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="col-lg-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.NameSurname)
                                @Html.TextBoxFor(model => model.NameSurname, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.NameSurname) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title)
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Title) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Username)
                                @Html.TextBoxFor(model => model.Username, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Username) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Password)
                                @Html.PasswordFor(model => model.Password, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Password) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ConfirmPassword)
                                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.ConfirmPassword) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Email)
                                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Email) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProfileImage)
                                <input name="ProfileImage" id="ProfileImage" type="file">
                            </div>
                            <button type="submit" class="btn btn-success">Yeni Yazar Ekle</button>
                            <button type="reset" class="btn btn-danger">İptal</button>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Facebook)
                                @Html.TextBoxFor(model => model.Facebook, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Facebook) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Twitter)
                                @Html.TextBoxFor(model => model.Twitter, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Twitter) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Github)
                                @Html.TextBoxFor(model => model.Github, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Github) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.LinkedIn)
                                @Html.TextBoxFor(model => model.LinkedIn, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.LinkedIn) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.WebSite)
                                @Html.TextBoxFor(model => model.WebSite, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.WebSite) })
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

src/BlogApp/Areas/Admin/Views/Authors/Edit.cshtml
@model BlogApp.Areas.Admin.Models.AuthorModel
@{
    bool IsError = false;
    bool IsMessage = false;
    string Message = "", Error = "";
    ViewBag.Title = "Yazar Güncelle";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Yazar Güncelle</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Yeni Yazar Ekle
            </div>
            <div class="panel-body">
                @if (IsError)
                {
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Error
                    </div>
                }
                else if (IsMessage)
                {
                    <div class="alert alert-success alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Message
                    </div>
                }
                <div class="row">
                    @using (Html.BeginForm("Edit", "Authors", new { area = "Admin" }, FormMethod.Post, true, new { role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.Id)
                        <div class="col-lg-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.NameSurname)
                                @Html.TextBoxFor(model => model.NameSurname, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.NameSurname) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title)
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Title) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Username)
                                @Html.TextBoxFor(model => model.Username, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Username) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Password)
                                @Html.PasswordFor(model => model.Password, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Password) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ConfirmPassword)
                                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.ConfirmPassword) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Email)
                                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Email) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.ProfileImage)
                                <input name="ProfileImage" id="ProfileImage" type="file">
                            </div>
                            <button type="submit" class="btn btn-success">Yazarı Güncelle</button>
                            <button type="reset" class="btn btn-danger">İptal</button>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.Facebook)
                                @Html.TextBoxFor(model => model.Facebook, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Facebook) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Twitter)
                                @Html.TextBoxFor(model => model.Twitter, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Twitter) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Github)
                                @Html.TextBoxFor(model => model.Github, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.Github) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.LinkedIn)
                                @Html.TextBoxFor(model => model.LinkedIn, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.LinkedIn) })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.WebSite)
                                @Html.TextBoxFor(model => model.WebSite, new { @class = "form-control", placeholder = Html.DisplayNameFor(model => model.WebSite) })
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

src/BlogApp/Areas/Admin/Views/Authors/Index.cshtml
@model List<BlogApp.Areas.Admin.Models.AuthorListModel>
@{ 
    ViewBag.Title = "Yazarlar";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Yazarlar</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Yazar Listesi
                <a type="button" asp-controller="Authors" asp-action="Add" class="btn btn-primary btn-sm pull-right">Yeni Yazar Ekle</a>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>Resim</th>
                            <th>Adı Soyadı</th>
                            <th>Ünvan</th>
                            <th>Mail Adres</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var author in Model)
                        {
                            <tr class="odd gradeX">
                                <td>
                                    <img style="border-radius:50%;" src="@author.ProfileImage" width="50" height="50" />
                                </td>
                                <td>@author.FullName</td>
                                <td>@author.Title</td>
                                <td class="center">
                                    @author.Email
                                </td>
                                <td class="center">
                                    @Html.ActionLink("Düzenle", "Edit", new { Id = author.Id })
                                    <button onclick="Delete('@author.Id')">Sil</button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Styles{
    <!-- DataTables CSS -->
    <link href="/assets/admin/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="/assets/admin/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

}

@section Scripts{
    <!-- DataTables JavaScript -->
    <script src="/assets/admin/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="/assets/admin/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/assets/admin/vendor/datatables-responsive/dataTables.responsive.js"></script>

    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });

        function Delete(id) {
            if (confirm("Yazarı silmek istediğinizden emin misiniz?")) {
                $.ajax({
                    method: 'POST',
                    url: '@Url.Action("Delete", "Authors")',
                    data: 'Id=' + id,
                    success: function (result) {
                        alert(result);
                        location.reload();
                    },
                    error: function (error) {
                        alert(error);
                    }
                });
            }
        }
    </script>
}